listen: :${SERVER_PORT}

tls:
  cert: /etc/hysteria/cert.pem
  key: /etc/hysteria/private.key

auth:
  type: password
  password: your_password

masquerade:
  type: proxy
  proxy:
    url: https://bing.com
    rewriteHost: true
